{
  project(fullPath: "psd/integration-suite") {
    name
    pipelines($pipelines_filter) {
      edges {
        node {
          id
          source
          createdAt
          status
          duration
          commitPath
          ref
          jobs {
            edges {
              node {
                id
                name
                status
                kind
                webPath
                duration
                trace {
                  htmlSummary(lastLines: 35)
                }
              }
            }
          }
        }
      }
    }
  }
}
